# Generated by Django 4.0.4 on 2022-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=60)),
                ('permalink', models.CharField(max_length=12, unique=True)),
                ('aggiornamento', models.DateTimeField(verbose_name='Ultimo Aggionrnamento')),
                ('testo', models.TextField(blank=True, verbose_name='Contenuto')),
            ],
        ),
    ]
